// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: notice.proto

package server

import (
	"context"

	"github.com/jialechen7/go-lottery/app/notice/cmd/rpc/internal/logic"
	"github.com/jialechen7/go-lottery/app/notice/cmd/rpc/internal/svc"
	"github.com/jialechen7/go-lottery/app/notice/cmd/rpc/pb"
)

type NoticeServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedNoticeServer
}

func NewNoticeServer(svcCtx *svc.ServiceContext) *NoticeServer {
	return &NoticeServer{
		svcCtx: svcCtx,
	}
}

func (s *NoticeServer) NoticeWishSign(ctx context.Context, in *pb.NoticeWishSignInReq) (*pb.NoticeWishSignInResp, error) {
	l := logic.NewNoticeWishSignLogic(ctx, s.svcCtx)
	return l.NoticeWishSign(in)
}
