// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	lottery "github.com/jialechen7/go-lottery/app/lottery/cmd/api/internal/handler/lottery"
	"github.com/jialechen7/go-lottery/app/lottery/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取当前抽奖中奖者名单
				Method:  http.MethodPost,
				Path:    "/lottery/getLotteryWinnersList",
				Handler: lottery.GetLotteryWinListHandler(serverCtx),
			},
			{
				// 获取抽奖列表
				Method:  http.MethodPost,
				Path:    "/lottery/lotteryList",
				Handler: lottery.LotteryListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/lottery/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 发起抽奖
				Method:  http.MethodPost,
				Path:    "/lottery/createLottery",
				Handler: lottery.CreateLotteryHandler(serverCtx),
			},
			{
				// 获取当前用户中奖列表
				Method:  http.MethodPost,
				Path:    "/lottery/getLotteryWinList",
				Handler: lottery.GetUserLotteryWinListHandler(serverCtx),
			},
			{
				// 抽奖详情
				Method:  http.MethodPost,
				Path:    "/lottery/lotteryDetail",
				Handler: lottery.LotteryDetailHandler(serverCtx),
			},
			{
				// 登录后获取抽奖列表
				Method:  http.MethodPost,
				Path:    "/lottery/lotteryListAfterLogin",
				Handler: lottery.LotteryListAfterLoginHandler(serverCtx),
			},
			{
				// 抽奖人
				Method:  http.MethodPost,
				Path:    "/lottery/participations",
				Handler: lottery.SearchParticipationHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/lottery/v1"),
	)
}
