// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	lottery "github.com/jialechen7/go-lottery/app/lottery/cmd/api/internal/handler/lottery"
	"github.com/jialechen7/go-lottery/app/lottery/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取抽奖列表
				Method:  http.MethodPost,
				Path:    "/lottery/lotteryList",
				Handler: lottery.LotteryListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/lottery/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 登录后获取抽奖列表
				Method:  http.MethodPost,
				Path:    "/lottery/lotteryListAfterLogin",
				Handler: lottery.LotteryListAfterLoginHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/lottery/v1"),
	)
}
